# Generated by Django 4.0.6 on 2022-07-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='number1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
