# Generated by Django 4.0.6 on 2022-07-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_home_number1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='number1',
        ),
    ]
