# Generated by Django 4.0.6 on 2022-07-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_home_number1'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='f_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
